import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { NotFoundError } from "@/lib/errors/app-error";
import { formatEGP } from "@/lib/money";
import { getCustomerCustomRequest } from "@/modules/custom-requests";

export default async function CustomRequestDetailPage({ params }: { params: Promise<{ requestNumber: string }> }) {
  const { requestNumber } = await params;
  let request;
  try { request = await getCustomerCustomRequest(requestNumber); }
  catch (error) { if (error instanceof NotFoundError) notFound(); throw error; }
  return <main className="mx-auto w-full max-w-5xl px-5 py-12 sm:px-8 lg:px-12 lg:py-20"><Link href="/account/custom-requests" className="label-caps underline underline-offset-4">Back to requests</Link><header className="mt-8 border-b border-outline-variant pb-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="label-caps text-on-surface-variant">{request.requestNumber}</p><h1 className="mt-3 headline-lg">{request.title}</h1></div><span className="border border-primary px-3 py-1 label-caps">{request.status}</span></div></header><section className="mt-8 border border-outline-variant bg-surface p-6 sm:p-8"><h2 className="headline-sm">Your request</h2><p className="mt-5 whitespace-pre-line body-md text-on-surface-variant">{request.description}</p><dl className="mt-7 grid gap-5 border-t border-outline-variant pt-6 body-sm sm:grid-cols-2 lg:grid-cols-3"><div><dt className="label-caps text-on-surface-variant">Quantity</dt><dd className="mt-2">{request.quantity}</dd></div>{request.material && <div><dt className="label-caps text-on-surface-variant">Material</dt><dd className="mt-2">{request.material}</dd></div>}{request.dimensions && <div><dt className="label-caps text-on-surface-variant">Dimensions</dt><dd className="mt-2">{request.dimensions}</dd></div>}{request.colors.length > 0 && <div><dt className="label-caps text-on-surface-variant">Colors</dt><dd className="mt-2">{request.colors.join(", ")}</dd></div>}{request.desiredDate && <div><dt className="label-caps text-on-surface-variant">Desired date</dt><dd className="mt-2">{new Intl.DateTimeFormat("en-EG", { dateStyle: "medium" }).format(new Date(request.desiredDate))}</dd></div>}{(request.budgetMinAmount !== undefined || request.budgetMaxAmount !== undefined) && <div><dt className="label-caps text-on-surface-variant">Budget</dt><dd className="mt-2">{request.budgetMinAmount !== undefined ? formatEGP(request.budgetMinAmount) : "Open"} – {request.budgetMaxAmount !== undefined ? formatEGP(request.budgetMaxAmount) : "Open"}</dd></div>}</dl>{request.referenceImages.length > 0 && <div className="mt-8 border-t border-outline-variant pt-6"><h2 className="headline-sm">Reference images</h2><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{request.referenceImages.map((image) => <div key={image.publicId} className="relative aspect-4/5 border border-outline-variant bg-[#F7F7F5]"><Image src={image.url} alt="Reference image" fill className="object-contain p-2" /></div>)}</div></div>}</section></main>;
}
