"use client";
import { useActionState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import type { ActionResult } from "@/lib/results/action-result";
import { saveShippingRateAction } from "@/modules/shipping/admin-actions";
import type { AdminShippingRateDTO } from "@/modules/shipping/admin-repository";
const initial: ActionResult<{ governorateCode: string } | null> = { ok: true, data: null };
export function ShippingRateForm({ rate }: { rate: AdminShippingRateDTO }) { const [state, action, pending] = useActionState(saveShippingRateAction, initial); const errors = state.ok ? undefined : state.error.fieldErrors; return <form action={action} className="grid gap-4 border-b border-outline-variant px-4 py-5 md:grid-cols-[minmax(9rem,1fr)_8rem_7rem_7rem_7rem] md:items-end"><input type="hidden" name="governorateCode" value={rate.governorateCode} /><div><p className="font-medium">{rate.governorateName}</p><p className="body-sm text-on-surface-variant">{rate.isConfigured ? "Configured" : "Not configured"}</p></div><label><span className="label-caps">Fee EGP</span><input name="fee" inputMode="decimal" defaultValue={(rate.feeAmount / 100).toFixed(2)} className="mt-2 w-full border-b border-outline-variant bg-transparent py-2 body-sm" />{errors?.feeAmount?.[0] ? <span className="body-sm text-error">{errors.feeAmount[0]}</span> : null}</label><label><span className="label-caps">Min days</span><input name="minDeliveryDays" type="number" min="1" defaultValue={rate.minDeliveryDays} className="mt-2 w-full border-b border-outline-variant bg-transparent py-2 body-sm" /></label><label><span className="label-caps">Max days</span><input name="maxDeliveryDays" type="number" min="1" defaultValue={rate.maxDeliveryDays} className="mt-2 w-full border-b border-outline-variant bg-transparent py-2 body-sm" /></label><div><Checkbox name="isActive" label="Active" defaultChecked={rate.isActive} className="mb-1" /><Button type="submit" disabled={pending} className="w-full px-3">{pending ? "Saving…" : "Save"}</Button></div>{!state.ok ? <p role="alert" className="body-sm text-error md:col-span-5">{state.error.message}</p> : state.message ? <p role="status" className="body-sm md:col-span-5">{state.message}</p> : null}</form>; }
