import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ requireAdmin: vi.fn(), transition: vi.fn(), whatsapp: vi.fn(), productCache: vi.fn(), path: vi.fn() }));
vi.mock("next/cache", () => ({ revalidatePath: mocks.path })); vi.mock("@/modules/auth/dal", () => ({ requireAdmin: mocks.requireAdmin })); vi.mock("@/modules/catalog/queries", () => ({ revalidateProductCache: mocks.productCache })); vi.mock("@/modules/orders/admin-service", () => ({ transitionAdminOrder: mocks.transition, recordAdminWhatsAppResult: mocks.whatsapp }));
import { recordWhatsAppResultAction, transitionOrderAction } from "@/modules/orders/admin-actions";
describe("admin order actions", () => { beforeEach(() => { vi.clearAllMocks(); mocks.requireAdmin.mockResolvedValue({ user: { id: "admin-1" } }); mocks.transition.mockResolvedValue({ productTargets: [{ id: "product-1", slug: "linen-bag" }] }); mocks.whatsapp.mockResolvedValue({ productTargets: [] }); });
  it("authorizes before validating transitions", async () => { const result = await transitionOrderAction(new FormData()); expect(mocks.requireAdmin).toHaveBeenCalledOnce(); expect(mocks.transition).not.toHaveBeenCalled(); expect(result.ok).toBe(false); });
  it("records the authenticated actor and invalidates restored product caches", async () => { const form = new FormData(); form.set("orderNumber", "AFN-1"); form.set("status", "CANCELLED"); form.set("note", "Customer cancelled"); const result = await transitionOrderAction(form); expect(mocks.transition).toHaveBeenCalledWith("AFN-1", "CANCELLED", "admin-1", "Customer cancelled"); expect(mocks.productCache).toHaveBeenCalledWith("product-1", "linen-bag"); expect(result.ok).toBe(true); });
  it("does not mark contact merely by generating a link", async () => { expect(mocks.whatsapp).not.toHaveBeenCalled(); const form = new FormData(); form.set("orderNumber", "AFN-1"); form.set("result", "CONTACTED"); await recordWhatsAppResultAction(form); expect(mocks.whatsapp).toHaveBeenCalledWith("AFN-1", "CONTACTED", "admin-1", undefined); });
});
